# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-08-07 06:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=255)),
                ('access_token', models.CharField(max_length=255)),
                ('key', models.CharField(max_length=255, unique=True)),
                ('expires', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
